Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/ubuntu-20.04"
  c.vm.hostname = "default-ubuntu-2004.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/home/svrazovski/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-errbit-default-ubuntu-2004-070b63c6-aaed-4dcf-b94a-fc4bead69c27"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
